to utilize firstParagraphTransitions.txt when compiling essay
LittlestCube/TheEssayWriter pull request #2
Opened 2018-11-15 21:37 UTC by JandJ101

You may want to check and see if this works before you make a new release or merge it.

2018-11-18 02:20 UTC, LittlestCube commented
Ah, thank you.

Unfortunately I cannot test anything at the moment, there is a certain absurd bug that I have spent months after months trying to fix. The code is here in the repo, it's just not in the v1.4.2 release because, well, it doesn't work.

As soon as I get that up and running I'll let you know, and I'll test these changes as well.

2018-11-18 22:08 UTC, JandJ101 commented
Sounds good!

2018-11-18 22:12 UTC, JandJ101 commented
I also made some changes to outputwriter,java to actually use the txt file. I don't know if you saw that. It's in my fork of the project. My fork might be a bit out of date.

https://github.com/JandJ101/TheEssayWriter/blob/master/outputwriter.java

2018-11-18 22:56 UTC, LittlestCube commented
It says your fork is 7 commits behind, maybe try pulling and see if the differences aren't too bad and maybe you can still merge?

2018-11-19 00:22 UTC, n8x0b7T commented
i think i have it fixed now.
https://github.com/JandJ101/TheEssayWriter/blob/master/outputwriter.java

2018-11-19 00:31 UTC, LittleCube-hax requested changes
There are a few changes that need to be made, not huge, but they will give errors if left in.

2018-11-19 00:32 UTC, LittlestCube commented on outputwriter.java
> +      InputStream in = EssayWriter.class.getResourceAsStream("firstParagraphTransitions.txt");
The file `firstParagraphTransitions.txt` doesn't exist.

2018-11-19 00:34 UTC, LittlestCube commented on outputwriter.java
> +      Random rand = new Random();
If you initialize two Random objects (see line 97), they either have to be given different names, or you have to use the same object. Preferably the latter. So all you have to do (if I'm thinking correctly) is erase line 97 and leave your line 94 in.

2019-09-02 19:52 UTC, closed without merging